version: '3.9'

services:
  web:
    build: .
    container_name: drf_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    
  
  db:
    container_name: drf_db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgres/data
  
volumes:
  pgdata: {}
  